Region:
Image:
  Os: alinux2
HeadNode:
  InstanceType: 
  Networking:
    SubnetId: 
  Ssh:
    KeyName: 
  Dcv:
    Enabled: true  
  Iam:
    S3Access:
      - EnableWriteAccess: true
        BucketName: '*'
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore    
  CustomActions:
    OnNodeStart:
      Script: s3://tempbucket/bootstrap-scripts/pcluster-on-node-start.sh
    OnNodeConfigured:
      Script:            
  Imds:
    Secured: false
Scheduling:
  Scheduler: awsbatch
  AwsBatchQueues:
    - Name: queue1
      CapacityType: SPOT
      ComputeResources:
        - Name: optimal
          InstanceTypes:
            - 
          MinvCpus: 
          DesiredvCpus: 
          MaxvCpus: 
          SpotBidPercentage:
      Networking:
        SubnetIds:
        - 
